[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:main]
command=bash -c 'python main.py --config %(ENV_MAIN_CONFIG)s 2>&1 | tee -a /app/logs/main.log'
user=%(ENV_APP_USER)s
autostart=%(ENV_ENABLE_MAIN)s
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
startsecs=5
startretries=3
stopasgroup=true
killasgroup=true

[program:grid]
command=bash -c 'python grid_main.py --config %(ENV_GRID_CONFIG)s 2>&1 | tee -a /app/logs/grid.log'
user=%(ENV_APP_USER)s
autostart=%(ENV_ENABLE_GRID)s
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
startsecs=5
startretries=3
stopasgroup=true
killasgroup=true
